/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers/$providerId'
import { Route as AdminResourceIndexRouteImport } from './routes/admin/$resource/index'
import { Route as WorkflowsWorkflowIdDeploymentsRouteImport } from './routes/workflows/$workflowId.deployments'
import { Route as AdminResourceNewRouteImport } from './routes/admin/$resource/new'
import { Route as AdminResourceRecordIdIndexRouteImport } from './routes/admin/$resource/$recordId/index'
import { Route as WorkflowsWorkflowIdExecutionsExecutionIdRouteImport } from './routes/workflows/$workflowId.executions.$executionId'
import { Route as AdminResourceRecordIdEditRouteImport } from './routes/admin/$resource/$recordId/edit'
import { Route as WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport } from './routes/workflows/$workflowId.deployments.$deploymentId.edit'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourceIndexRoute = AdminResourceIndexRouteImport.update({
  id: '/$resource/',
  path: '/$resource/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkflowsWorkflowIdDeploymentsRoute =
  WorkflowsWorkflowIdDeploymentsRouteImport.update({
    id: '/workflows/$workflowId/deployments',
    path: '/workflows/$workflowId/deployments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminResourceNewRoute = AdminResourceNewRouteImport.update({
  id: '/$resource/new',
  path: '/$resource/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourceRecordIdIndexRoute =
  AdminResourceRecordIdIndexRouteImport.update({
    id: '/$resource/$recordId/',
    path: '/$resource/$recordId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const WorkflowsWorkflowIdExecutionsExecutionIdRoute =
  WorkflowsWorkflowIdExecutionsExecutionIdRouteImport.update({
    id: '/workflows/$workflowId/executions/$executionId',
    path: '/workflows/$workflowId/executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminResourceRecordIdEditRoute =
  AdminResourceRecordIdEditRouteImport.update({
    id: '/$resource/$recordId/edit',
    path: '/$resource/$recordId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute =
  WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport.update({
    id: '/$deploymentId/edit',
    path: '/$deploymentId/edit',
    getParentRoute: () => WorkflowsWorkflowIdDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/admin/$resource/new': typeof AdminResourceNewRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/admin/$resource': typeof AdminResourceIndexRoute
  '/admin/$resource/$recordId/edit': typeof AdminResourceRecordIdEditRoute
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/admin/$resource/$recordId': typeof AdminResourceRecordIdIndexRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/admin/$resource/new': typeof AdminResourceNewRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/admin/$resource': typeof AdminResourceIndexRoute
  '/admin/$resource/$recordId/edit': typeof AdminResourceRecordIdEditRoute
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/admin/$resource/$recordId': typeof AdminResourceRecordIdIndexRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/admin/$resource/new': typeof AdminResourceNewRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/admin/$resource/': typeof AdminResourceIndexRoute
  '/admin/$resource/$recordId/edit': typeof AdminResourceRecordIdEditRoute
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/admin/$resource/$recordId/': typeof AdminResourceRecordIdIndexRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/setup'
    | '/upgrade'
    | '/providers/$providerId'
    | '/admin/'
    | '/profile'
    | '/providers'
    | '/settings'
    | '/workflows'
    | '/admin/$resource/new'
    | '/workflows/$workflowId/deployments'
    | '/admin/$resource'
    | '/admin/$resource/$recordId/edit'
    | '/workflows/$workflowId/executions/$executionId'
    | '/admin/$resource/$recordId'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/setup'
    | '/upgrade'
    | '/providers/$providerId'
    | '/admin'
    | '/profile'
    | '/providers'
    | '/settings'
    | '/workflows'
    | '/admin/$resource/new'
    | '/workflows/$workflowId/deployments'
    | '/admin/$resource'
    | '/admin/$resource/$recordId/edit'
    | '/workflows/$workflowId/executions/$executionId'
    | '/admin/$resource/$recordId'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/setup'
    | '/upgrade'
    | '/providers/$providerId'
    | '/admin/'
    | '/profile/'
    | '/providers/'
    | '/settings/'
    | '/workflows/'
    | '/admin/$resource/new'
    | '/workflows/$workflowId/deployments'
    | '/admin/$resource/'
    | '/admin/$resource/$recordId/edit'
    | '/workflows/$workflowId/executions/$executionId'
    | '/admin/$resource/$recordId/'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  UpgradeRoute: typeof UpgradeRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsWorkflowIdDeploymentsRoute: typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  WorkflowsWorkflowIdExecutionsExecutionIdRoute: typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$resource/': {
      id: '/admin/$resource/'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workflows/$workflowId/deployments': {
      id: '/workflows/$workflowId/deployments'
      path: '/workflows/$workflowId/deployments'
      fullPath: '/workflows/$workflowId/deployments'
      preLoaderRoute: typeof WorkflowsWorkflowIdDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$resource/new': {
      id: '/admin/$resource/new'
      path: '/$resource/new'
      fullPath: '/admin/$resource/new'
      preLoaderRoute: typeof AdminResourceNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$resource/$recordId/': {
      id: '/admin/$resource/$recordId/'
      path: '/$resource/$recordId'
      fullPath: '/admin/$resource/$recordId'
      preLoaderRoute: typeof AdminResourceRecordIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workflows/$workflowId/executions/$executionId': {
      id: '/workflows/$workflowId/executions/$executionId'
      path: '/workflows/$workflowId/executions/$executionId'
      fullPath: '/workflows/$workflowId/executions/$executionId'
      preLoaderRoute: typeof WorkflowsWorkflowIdExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$resource/$recordId/edit': {
      id: '/admin/$resource/$recordId/edit'
      path: '/$resource/$recordId/edit'
      fullPath: '/admin/$resource/$recordId/edit'
      preLoaderRoute: typeof AdminResourceRecordIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workflows/$workflowId/deployments/$deploymentId/edit': {
      id: '/workflows/$workflowId/deployments/$deploymentId/edit'
      path: '/$deploymentId/edit'
      fullPath: '/workflows/$workflowId/deployments/$deploymentId/edit'
      preLoaderRoute: typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport
      parentRoute: typeof WorkflowsWorkflowIdDeploymentsRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminResourceNewRoute: typeof AdminResourceNewRoute
  AdminResourceIndexRoute: typeof AdminResourceIndexRoute
  AdminResourceRecordIdEditRoute: typeof AdminResourceRecordIdEditRoute
  AdminResourceRecordIdIndexRoute: typeof AdminResourceRecordIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminResourceNewRoute: AdminResourceNewRoute,
  AdminResourceIndexRoute: AdminResourceIndexRoute,
  AdminResourceRecordIdEditRoute: AdminResourceRecordIdEditRoute,
  AdminResourceRecordIdIndexRoute: AdminResourceRecordIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface WorkflowsWorkflowIdDeploymentsRouteChildren {
  WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute: typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}

const WorkflowsWorkflowIdDeploymentsRouteChildren: WorkflowsWorkflowIdDeploymentsRouteChildren =
  {
    WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute:
      WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute,
  }

const WorkflowsWorkflowIdDeploymentsRouteWithChildren =
  WorkflowsWorkflowIdDeploymentsRoute._addFileChildren(
    WorkflowsWorkflowIdDeploymentsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  UpgradeRoute: UpgradeRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsWorkflowIdDeploymentsRoute:
    WorkflowsWorkflowIdDeploymentsRouteWithChildren,
  WorkflowsWorkflowIdExecutionsExecutionIdRoute:
    WorkflowsWorkflowIdExecutionsExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
